package com.athaydes;

import java.io.Serializable;
import java.util.Date;

/**
 * Dummy POJO used for testing.
 */
public class Person implements Serializable {

    /**
     * Version UID for Serialization
     */
    private static final long serialVersionUID = 1;

    /**
     * Identity is generated by DB.  From 0-BIGINT.
     */
    private Long identity = 0L;

    private String name;
    private String favouriteColour;

    /**
     * Date the object was created
     */
    private Date lastUpdated = new Date();

    private Person() {
        // serialization
    }

    public Person( String name ) {
        this.name = name;
    }

    public Long getIdentity() {
        return identity;
    }

    public Date getLastUpdated() {
        return lastUpdated;
    }

    public String getName() {
        return name;
    }

    public String getFavouriteColour() {
        return favouriteColour;
    }

    public void setFavouriteColour( String favouriteColour ) {
        this.favouriteColour = favouriteColour;
    }
}
